### ISSUE TITLE
Seems to produce overly-complex codes for large input data

### ISSUE THREAD

**Issue by giftig** [davidshimjs/qrcodejs#105]
I'm comparing the output of this script with the version produced by the qrencode unix tool and it seems for a sample I'm using, the js produces a QR code which is far larger than it needs to be (compared to the unix tool), which results in it being too detailed for my camera to recognise it.

I'm using a 734-character input to try it out, and the below images are the outputs of this library vs the unix tool (which I'm calling with ```docker run --rm giftig/qrencode -o - "$DATA"```)

Please ignore the content, it's a set of notes for myself. I considered writing some sample nonsense to post instead but I don't mind the internet knowing about my quest to do some electrical work on my house.

![davidshimjs-qrcode](https://cloud.githubusercontent.com/assets/2862039/21752403/1a1cbb08-d5cf-11e6-9598-44150cc91b9c.png)

![qrencode-qrcode](https://cloud.githubusercontent.com/assets/2862039/21752407/24087f44-d5cf-11e6-8360-5e647a3b8232.png)

Forgive my ignorance of the details of how QR encoding works; I can't really speculate on what you're doing differently, but the result is clearly a far less space-optimised result. The latter image is recognised easily my by phone, and the former I have no doubt is a valid encoding of the same data, but is far too detailed to be viable.

**Comment by mix3d** [comment]
Speculation: It is probably hardcoded to a high "error rate" value.

**Comment by JvdBossche** [comment]
I have a ~400 character URL to encode (lots of parameters with long values)
The QR code was so complex that it couldn't be scanned!

According to [https://en.wikipedia.org/wiki/QR_code#Error_correction](https://en.wikipedia.org/wiki/QR_code#Error_correction) the error correction levels are known as "L", "M", "Q" and "H".
The sample code "with options" contains a line
`correctLevel : QRCode.CorrectLevel.H`
I added such a line, but changed it to
`correctLevel : QRCode.CorrectLevel.L`
Then the generated QR code looked a lot simpler and was scanned without problems.
