### ISSUE TITLE
Security question!!!

### ISSUE THREAD

**Issue by qrLogin** [davidshimjs/qrcodejs#143]
Question on safety!
Is qrcode generated by this library stored in the browser cache?
I could not find the exact confirmation, yes or no ((
Browsers write that the code from the memory cache rises ... but whether they keep it on the disk is not clear (((
This affects the safe use of secret data in the code!

**Comment by phamhuyvn** [comment]
Not cache, it is base64 string make by browser and appen to img tag, not a real image

**Comment by qrLogin** [comment]
And base64 strings do not remain in the browser cache?
Where is that there is confirmation of this?

**Comment by phamhuyvn** [comment]
Files that are cached locally include any documents that make up a website, such as html files, CSS style sheets, JavaScript scripts, as well as graphic images and other multimedia content.

but base64 string is a variable ( not in your source code ) and not caching.
for more info : https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

**Comment by qrLogin** [comment]
Thank you very much
