### ISSUE TITLE
_android not work

### ISSUE THREAD

**Issue by YangDaniu** [davidshimjs/qrcodejs#148]
![image](https://user-images.githubusercontent.com/10378466/35033180-9bc21dc8-fba4-11e7-9324-28d5df13236f.png)

Here this is window and this._android === undefined

**Comment by shivpatel** [comment]
Getting the same issue. Any luck?

**Update:** If you're ok with dropping Android 2.1 support, just use the un-minified .js file and comment out lines 283 through 301. Seems to work fine after that.
