### ISSUE TITLE
no release？ no npm? no bower?

### ISSUE THREAD

**Issue by Clinan** [davidshimjs/qrcodejs#172]
I just find it in npm, but updated three years ago。

**Comment by Zemke** [comment]
I was wondering as well but it could still be up-to-date since the last commit is also five years ago.

https://www.npmjs.com/package/qrcodejs

Edit: This is apparently not official, though, coming from a fork. What I've done now is

```
yarn add https://github.com/davidshimjs/qrcodejs#04f46c6a0708418cb7b96fc563eacae0fbf77674
```

**Comment by Walkman100** [comment]
@Zemke 
> Edit: This is apparently not official, though, coming from a fork. What I've done now is [...]

There's also https://www.npmjs.com/package/qrcodejs2 which I saw in another issue, don't know if it's official but at least the npm page points to this repo and not a different one.
