### ISSUE TITLE
If You Have Code Length Overflow Error or Want Additional White Border, Check This

### ISSUE THREAD

**Issue by zhiyuan-l** [davidshimjs/qrcodejs#177]
Hey guys, I've been using this tool in my project and have encountered few frustrations, like code length overflow error and QR code border. I've found solutions in different threads, but they did not solve these problems at once. So, I forked this project and merged the solutions. Now you can use my fork in your project since the author is not going to merge all the pull requests.
https://github.com/zhiyuan-l/qrcodejs 
Sources
#109 for Code Length Overflow Error
#54 for new border parameter

Thanks to the providers of these solutions.

**Comment by Syarit** [comment]
Thank you so much, you saved me
