### ISSUE TITLE
Need an example with SVG on Basic Usages

### ISSUE THREAD

**Issue by martinrios95** [davidshimjs/qrcodejs#193]
Hi,

I need an example on your GitHub Page to use this library when I want to make an SVG image.
I need this to make a QR code on SVG to enhance printing.

Best wishes,

Martin

**Comment by darosior** [comment]
Hi,

Checkout the example here : https://github.com/davidshimjs/qrcodejs/blob/master/index-svg.html . You just have to set `useSVG` to `true`.

**Comment by martinrios95** [comment]
Thank you for the quick guide... But I suggest to put an example **on their GitHub page**...
