### ISSUE TITLE
mate30 支持不了生成二维码，有谁解决了吗？

### ISSUE THREAD

**Issue by birdy0815** [davidshimjs/qrcodejs#210]
mate30 支持不了生成二维码，有谁解决了吗？

**Comment by Zhantrywei** [comment]
我也遇到类似bug,好像不是不能生成二维码,qrcodejs能生成二维码的canvas,但是华为手机和小米手机在微信webview中无法把canvas里面的base64导出来给canvas的兄弟节点的img的src,所以再次利用这个兄弟节点img的src绘制二维码合成海报就会无法展示二维码.我的解决方法是重新把qrcode下的canvas再导一次base64出来当src就可以了.不知道是否和你遇到的问题一致.
`qr.src=document.getElementById("qrcode").children[0].toDataURL("image/png")`

**Comment by birdy0815** [comment]
通过这个issue可以解决问题，不是兼容问题，是系统版本判断有误。

https://github.com/davidshimjs/qrcodejs/issues/175

**Comment by SkyLandBeast** [comment]
安卓10和10以上无法画出二维码，因为作者的正则过时了，当时作者写表达式匹配的时候手机还没有出道安卓10以上
qrcode.js _getAndroid 方法里面的正则判断改为：var aMat = sAgent.toString().match(/([aA])ndroid ([0-9.]*)/i);
