### ISSUE TITLE
vCard QR-Code is not scannable

### ISSUE THREAD

**Issue by iAmOnGitHubNow** [davidshimjs/qrcodejs#227]
When I generate a QR-Code from a .vcf-file the code appears, but I can't scan it. I tried different Correction Levels, types and scanners.
Here is a generated Example-Code:
![image](https://user-images.githubusercontent.com/64193052/80076855-0620a480-854d-11ea-942b-8f3152876203.png)

**Comment by vswee** [comment]
I am able to scan it using an iPhone and the default camera app

**Comment by iAmOnGitHubNow** [comment]
Ok thanks. I guess I should switch the app or phone then.
