### ISSUE TITLE
华为手机出现问题

### ISSUE THREAD

**Issue by WangHao1221** [davidshimjs/qrcodejs#234]
华为emui 9，小程序中出现问题，是适配安卓9以上出现问题了吗？

**Comment by WangHao1221** [comment]
加上延时，并且要设置大一点就可以了

**Comment by SkyLandBeast** [comment]
安卓10和10以上无法画出二维码，因为作者的正则过时了，当时作者写表达式匹配的时候手机还没有出道安卓10以上
qrcode.js _getAndroid 方法里面的正则判断改为：var aMat = sAgent.toString().match(/([aA])ndroid ([0-9\.]*)/i);

**Comment by WangHao1221** [comment]
好的 谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SkyLandBeast ***@***.***&gt;
发送时间: 2021年8月9日 15:39
收件人: davidshimjs/qrcodejs ***@***.***&gt;
抄送: peterWang ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[davidshimjs/qrcodejs] 华为手机出现问题 (#234)





 
安卓10和10以上无法画出二维码，因为作者的正则过时了，当时作者写表达式匹配的时候手机还没有出道安卓10以上
 qrcode.js _getAndroid 方法里面的正则判断改为：var aMat = sAgent.toString().match(/([aA])ndroid ([0-9.]*)/i);
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
