### ISSUE TITLE
If string length is large then qr code is not scanning.

### ISSUE THREAD

**Issue by ErVishalM** [davidshimjs/qrcodejs#246]
Hi,

I was using qrcodejs and if I want to type this string `eyJhbGciOiJSUzI1NiIsImtpZCI6IkVEQzU3REUxMzU4QjMwMEJBOUY3OTM0MEE2Njk2ODMxRjNDODUwNDciLCJ0eXAiOiJKV1QiLCJ4NXQiOiI3Y1Y5NFRXTE1BdXA5NU5BcG1sb01mUElVRWMifQ.eyJkYXRhIjoie1wiU2VsbGVyR3N0aW5cIjpcIjI5QUFGQ0Q1ODYyUjAwMFwiLFwiQnV5ZXJHc3RpblwiOlwiMjlBQUFDSjcyMzBOMVo4XCIsXCJEb2NOb1wiOlwiZmdrbWZna2xmZGctMDJcIixcIkRvY1R5cFwiOlwiSU5WXCIsXCJEb2NEdFwiOlwiMTcvMTEvMjAyMFwiLFwiVG90SW52VmFsXCI6MzMuMDQsXCJJdGVtQ250XCI6MSxcIk1haW5Ic25Db2RlXCI6XCI5NDAxXCIsXCJJcm5cIjpcIjlmMDdjMzFmNjVjYTJhZDM4ZTNjNDU1YTk0OGRkOTk5ZmM3OWE2YmE1NDA0ZDY2NzQ2MGJiZmY2MTJjNzBhODVcIixcIklybkR0XCI6XCIyMDIwLTExLTIzIDIwOjE1OjAwXCJ9IiwiaXNzIjoiTklDIn0.C-SpBoxsRyrtaZzDKJ7YeRus0Z0aBscUTOjL4vqvnu6yiubpdY3P0zfbUuwulbY8IQ4h4MtYazaNmJ497t_DlNGNi89tzIphFIpz-IZH576EW9rbnyaKvJcgqi5k8cljR8fn9p9kr0qpnbYU8eSABW4C-qd6oKhs3OPesHhrJDvW8zoq29_mzCz1SZEcMhyI8jtZXuJoLuN-AJIq9LII9n61aSVEeMOT1tqt4wiz1WfRlMfBaIRvEHHl0AIq2dMjSxuB58A15XCclBIg291aiXny41KuLcABnn0k3VKfUAcF2kpfzNrPO44fOn1I0NDvYgb_hp7y3Xa0lDX3b_Ay7A`
then qrcode scanner not scanning this qr code [URL](https://codepen.io/ErVishalM/pen/QWKaVPL) Can you please check and let me know Is there anything wrong I am doing.

Thanks.

**Comment by GabrielDvt** [comment]
Same here, any solutions?

**Comment by julkz** [comment]
I tried and it worked perfectly, so just wanna shout three things for you to try:
Mine worked perfectly, have you tried increasing the size of the image ? Also if you'r printing, its very important to go with 300dpi above

**Comment by julkz** [comment]
I tried and it worked perfectly, so just wanna say three things for you to try:
1. Increase the size of the image on screens.
2. If your printing, make sure you use a minimum of 300dpi.
3. If your using it for GET request, please keep notice that GET requests only allow a 2K maximum length, [https://developers.google.com/chart/infographics/docs/qr_codes], if you need more than 2k use the POST method.

**Comment by julkz** [comment]
Increase the size of the image on screens.
If your printing, make sure you use a minimum of 300dpi.
If your using it for GET request, please keep notice that GET requests only allow a 2K maximum length, [GoogleDocs](https://developers.google.com/chart/infographics/docs/qr_codes) , if you need more than 2k use the POST method.
