### ISSUE TITLE
url内容太多，生成的二维码扫不了

### ISSUE THREAD

**Issue by horizon188** [davidshimjs/qrcodejs#249]
width: 74,
        height: 74,
        text: "http://wxh5.beta.hqjy.com/article/709?siteId=1&informationTypeId=139&informationType=2&provinceId=0", // 
        colorDark: "#000",
        timer: null,
        colorLight: "#fff",
        correctLevel: this.$QRCode.CorrectLevel.L
![image](https://user-images.githubusercontent.com/37240607/120421266-8e03ef80-c398-11eb-940b-8ca3aced6a97.png)
是我生成的方式错了嘛？

**Comment by SkyLandBeast** [comment]
安卓10和10以上无法画出二维码，因为作者的正则过时了，当时作者写表达式匹配的时候手机还没有出道安卓10以上
qrcode.js _getAndroid 方法里面的正则判断改为：var aMat = sAgent.toString().match(/([aA])ndroid ([0-9.]*)/i);
