### ISSUE TITLE
chrome中生成的二维码不正常

### ISSUE THREAD

**Issue by hayye** [davidshimjs/qrcodejs#261]
![image](https://user-images.githubusercontent.com/30612116/140703558-2c222248-39c1-4422-8727-03f34d1f7300.png)
在chrome、Edge中运行生成的二维码是这样的，无法识别

**Comment by weiweian90** [comment]
same problem on some windows

**Comment by weiweian90** [comment]
> ![image](https://user-images.githubusercontent.com/30612116/140703558-2c222248-39c1-4422-8727-03f34d1f7300.png) 在chrome、Edge中运行生成的二维码是这样的，无法识别

这个库是不是不维护了？

**Comment by weiweian90** [comment]
> ![image](https://user-images.githubusercontent.com/30612116/140703558-2c222248-39c1-4422-8727-03f34d1f7300.png) 在chrome、Edge中运行生成的二维码是这样的，无法识别

这个和设备的分辨率有关，暂时可以通过更改源码解决该问题，问题出现在Drawing.prototype.draw中

**Comment by fuhao-w** [comment]
> > ![image](https://user-images.githubusercontent.com/30612116/140703558-2c222248-39c1-4422-8727-03f34d1f7300.png) 在chrome、Edge中运行生成的二维码是这样的，无法识别
> 
> 这个和设备的分辨率有关，暂时可以通过更改源码解决该问题，问题出现在Drawing.prototype.draw中
@weiweian90 
欸？确认是和分辨率有关吗？请问在哪种分辨率下会出这个问题呀？我这边遇到几个出问题的的全是11代的intel处理器，还以为和处理器有关呢。

**Comment by weiweian90** [comment]
> > > ![image](https://user-images.githubusercontent.com/30612116/140703558-2c222248-39c1-4422-8727-03f34d1f7300.png) 在chrome、Edge中运行生成的二维码是这样的，无法识别
> > 
> > 
> > 这个和设备的分辨率有关，暂时可以通过更改源码解决该问题，问题出现在Drawing.prototype.draw中
> > @weiweian90
> > 欸？确认是和分辨率有关吗？请问在哪种分辨率下会出这个问题呀？我这边遇到几个出问题的的全是11代的intel处理器，还以为和处理器有关呢。

可以参考下草料二维码的处理方式，他们也是用的qrcode.js, 不过是在服务端转成图片，页面中展示服务端下发的图片

**Comment by hayye** [comment]
解决了，问题原因在于11代intel核心显卡驱动问题，驱动更新到最新版本即可解决
