### ISSUE TITLE
Can't render text with line breaks

### ISSUE THREAD

**Issue by HardeepAsrani** [davidshimjs/qrcodejs#34]
A user of my WordPress plugin [Generate QR Code](http://wordpress.org/plugins/qr-code-by-tricks-panda/)!, which uses qrcode.js script and I noticed that we can't use line breaks in text to render QR Code.

Is it possible?

Thanks and amazing work :)

**Comment by corse-xx** [comment]
you can do \r\n to do a line break, at least that seems to be working for me
