### ISSUE TITLE
I use script tag to import qrcode.js, it works well, but when I package qrcode.js , it has a error.

### ISSUE THREAD

**Issue by treadpit** [davidshimjs/qrcodejs#91]
In main.js,  I use these code to import qrcode.js

`import "../lib/qrcode.min"`

Then I package it use webpack, and open the html in browser, in the console:

> Uncaught TypeError: Cannot read property '_android' of undefined

why? Can you help me? Thanks!

**Comment by wjs** [comment]
The save error for me. I modified the source code to make it works 😂

**Comment by markvantilburg** [comment]
see https://github.com/davidshimjs/qrcodejs/issues/84 the .min file is 3 years old where the non minified version is 2 years old...

**Comment by treadpit** [comment]
@markvantilburg get it, thanks
